language: node_js
node_js:
- stable
- '6'
- '4'
before_deploy:
  - "echo 'ready? 1 git subtree'"
  - "echo 'ready? 2 git subtree'"
deploy:
  provider: heroku
  api_key:
    secure: JEJZYcsU5ng8trEm0b767Kj5XgVW3YOQ9Cogb9xfPIo0PUoacjluJMVfzJb5NQuBTLbsAdB3TYLh0cGEFkUJ940Nka4PUP5+M7nPsRtwaE0Zjhj41lyE/rmULVpw7tvO4Plyr4h4By6bS2W0f0SQ/TCEPt6QXVo0yykee+Js1azyW2BFjsf3cgOlh/CP6pJHWegQ33QF3zAHdFf0XJZu5WKbwUwQooadYdzZ0slLdILVnruKOAft5rHOtNXK1tsa9UY+12ppfCGShi23OblT4E0/+vx/qv+Ev3Eo47MW8j2E8vDkjUAEHybFRMvJVQnfyZPmd9LVcPOkJgfFwa6soBHP+MyLek6FMMx/J9s/FZGzbcmD9+Ex3saIT5nKjHttI+PKv1H0TjsDht9t068II0/E+25vcjmIO/JYbMnpP3vFwh+5PEPIkrtHwINQxM4TKAbaxiAFTLQaSsKrUc0b0gN3Zf3mHtl4hhbAn5EgsbK2CY+9BufUOL4aJXBnhWWdCIVrRrBquVhzCx6flmZs3zYDpHB35OrxGFkDH7z6wbar8K2kYpKOLZ8xHsgw4QXovyzatChXqoeKcaySD983ICw6RcFoHSib9fUNnEz+FAqNJ8lpDU+Mm4kNDTvpg++Nzv3X1QyTePs9fZ460mTN2wzim3ebjVbEf8xs8x0XKoQ=
  app: lb-hero-app
  on:
    repo: Wilfongjt/lb-heroku-nuxtjs
  skip_cleanup: 'true'
